version: 1
project:
  name: litxr-project
  data_root: data/literature
collections:
  - collection_id: journal_of_finance
    collection_type: journal
    title: Journal of Finance
    remote_channel: crossref
    local_path: data/literature/journal_of_finance
    metadata:
      publisher: Wiley
      issn_print: 0022-1082
      issn_electronic: 1540-6261
    sync:
      filters:
        issn: 0022-1082
  - collection_id: journal_of_financial_economics
    collection_type: journal
    title: Journal of Financial Economics
    remote_channel: crossref
    local_path: data/literature/journal_of_financial_economics
    metadata:
      publisher: Elsevier
      issn_print: 0304-405X
    sync:
      filters:
        issn: 0304-405X
  - collection_id: arxiv_cs_ai
    collection_type: arxiv_category
    title: arXiv cs.AI
    remote_channel: arxiv
    local_path: data/literature/arxiv_cs_ai
    metadata:
      archive: arXiv
      category: cs.AI
    sync:
      search_query: cat:cs.AI
