builder <- function(ref, markdown, template) {
  title_value <- if (!is.null(ref$title) && length(ref$title) && nzchar(ref$title[[1]])) {
    ref$title[[1]]
  } else {
    ref$ref_id[[1]]
  }

  markdown_lines <- trimws(strsplit(markdown, "\n", fixed = TRUE)[[1]])
  markdown_lines <- markdown_lines[nzchar(markdown_lines)]
  first_line <- if (length(markdown_lines)) markdown_lines[[1]] else ""

  template$summary <- paste("Draft summary for", title_value)
  template$motivation <- if (nzchar(first_line)) {
    paste("Replace this placeholder. First markdown line:", first_line)
  } else {
    "Replace this placeholder with the paper's motivation."
  }
  template$research_questions <- c(
    "Replace this with the main research question."
  )
  template$methods <- c(
    "Replace this with the core empirical or theoretical method."
  )
  template$sample <- list(
    sample_period = NA_character_,
    sample_size = NA_character_,
    geography = NA_character_,
    data_sources = character()
  )
  template$key_findings <- c(
    "Replace this with the main finding."
  )
  template$limitations <- c(
    "Replace this with the main limitation."
  )
  template$keywords <- c("draft")
  template$notes <- "Generated by scripts/example_digest_builder.R. Edit this builder for real extraction logic."
  template
}
